CREATE TYPE "public"."grammatical_case" AS ENUM('nominative', 'genitive', 'dative', 'accusative', 'vocative');--> statement-breakpoint
CREATE TYPE "public"."degree" AS ENUM('comparative', 'superlative');--> statement-breakpoint
CREATE TYPE "public"."disclosure_level" AS ENUM('beginner', 'expanded', 'advanced');--> statement-breakpoint
CREATE TYPE "public"."experience_level" AS ENUM('none', 'beginner', 'intermediate');--> statement-breakpoint
CREATE TYPE "public"."gender" AS ENUM('masculine', 'feminine', 'neuter');--> statement-breakpoint
CREATE TYPE "public"."grammar_progress_status" AS ENUM('introduced', 'studied');--> statement-breakpoint
CREATE TYPE "public"."lesson_item_kind" AS ENUM('vocab', 'grammar', 'reading', 'review');--> statement-breakpoint
CREATE TYPE "public"."mood" AS ENUM('indicative', 'imperative', 'subjunctive', 'optative', 'infinitive', 'participle');--> statement-breakpoint
CREATE TYPE "public"."grammatical_number" AS ENUM('singular', 'plural');--> statement-breakpoint
CREATE TYPE "public"."part_of_speech" AS ENUM('adjective', 'conjunction', 'adverb', 'interjection', 'noun', 'preposition', 'article', 'demonstrative_pronoun', 'interrogative_indefinite_pronoun', 'personal_pronoun', 'relative_pronoun', 'verb', 'particle');--> statement-breakpoint
CREATE TYPE "public"."person" AS ENUM('first', 'second', 'third');--> statement-breakpoint
CREATE TYPE "public"."review_context" AS ENUM('review', 'lesson');--> statement-breakpoint
CREATE TYPE "public"."review_grade" AS ENUM('again', 'hard', 'good', 'easy');--> statement-breakpoint
CREATE TYPE "public"."tense" AS ENUM('present', 'imperfect', 'future', 'aorist', 'perfect', 'pluperfect');--> statement-breakpoint
CREATE TYPE "public"."testament" AS ENUM('NT');--> statement-breakpoint
CREATE TYPE "public"."voice" AS ENUM('active', 'middle', 'passive');--> statement-breakpoint
CREATE TABLE "grammar_concept_examples" (
	"concept_id" integer NOT NULL,
	"token_id" integer NOT NULL,
	"position" integer NOT NULL,
	CONSTRAINT "grammar_concept_examples_concept_id_token_id_pk" PRIMARY KEY("concept_id","token_id"),
	CONSTRAINT "grammar_concept_examples_position_unique" UNIQUE("concept_id","position")
);
--> statement-breakpoint
CREATE TABLE "grammar_concept_rules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "grammar_concept_rules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"concept_id" integer NOT NULL,
	"match" jsonb NOT NULL,
	"note" text,
	CONSTRAINT "grammar_concept_rules_match_nonempty_object" CHECK (jsonb_typeof("grammar_concept_rules"."match") = 'object' and "grammar_concept_rules"."match" <> '{}'::jsonb)
);
--> statement-breakpoint
CREATE TABLE "grammar_concepts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "grammar_concepts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"curriculum_order" integer NOT NULL,
	"title" text NOT NULL,
	"summary_simple" text NOT NULL,
	"body" text NOT NULL,
	"terminology_level" "disclosure_level" DEFAULT 'expanded' NOT NULL,
	CONSTRAINT "grammar_concepts_slug_unique" UNIQUE("slug"),
	CONSTRAINT "grammar_concepts_curriculum_order_unique" UNIQUE("curriculum_order"),
	CONSTRAINT "grammar_concepts_order_positive" CHECK ("grammar_concepts"."curriculum_order" > 0)
);
--> statement-breakpoint
CREATE TABLE "lesson_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lesson_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lesson_id" integer NOT NULL,
	"position" integer NOT NULL,
	"kind" "lesson_item_kind" NOT NULL,
	"lemma_id" integer,
	"concept_id" integer,
	"passage_id" integer,
	CONSTRAINT "lesson_items_position_unique" UNIQUE("lesson_id","position"),
	CONSTRAINT "lesson_items_target_matches_kind" CHECK (case "lesson_items"."kind"
        when 'vocab' then "lesson_items"."lemma_id" is not null and "lesson_items"."concept_id" is null and "lesson_items"."passage_id" is null
        when 'grammar' then "lesson_items"."concept_id" is not null and "lesson_items"."lemma_id" is null and "lesson_items"."passage_id" is null
        when 'reading' then "lesson_items"."passage_id" is not null and "lesson_items"."lemma_id" is null and "lesson_items"."concept_id" is null
        when 'review' then "lesson_items"."lemma_id" is null and "lesson_items"."concept_id" is null and "lesson_items"."passage_id" is null
      end)
);
--> statement-breakpoint
CREATE TABLE "lessons" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lessons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"curriculum_order" integer NOT NULL,
	"title" text NOT NULL,
	"passage_id" integer,
	CONSTRAINT "lessons_curriculum_order_unique" UNIQUE("curriculum_order"),
	CONSTRAINT "lessons_order_positive" CHECK ("lessons"."curriculum_order" > 0)
);
--> statement-breakpoint
CREATE TABLE "passage_required_concepts" (
	"passage_id" integer NOT NULL,
	"concept_id" integer NOT NULL,
	CONSTRAINT "passage_required_concepts_passage_id_concept_id_pk" PRIMARY KEY("passage_id","concept_id")
);
--> statement-breakpoint
CREATE TABLE "passages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "passages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"start_verse_id" integer NOT NULL,
	"end_verse_id" integer NOT NULL,
	"difficulty_score" real,
	"curriculum_order" integer,
	CONSTRAINT "passages_curriculum_order_unique" UNIQUE("curriculum_order"),
	CONSTRAINT "passages_range_unique" UNIQUE("start_verse_id","end_verse_id")
);
--> statement-breakpoint
CREATE TABLE "review_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "review_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"lemma_id" integer NOT NULL,
	"grade" "review_grade" NOT NULL,
	"reviewed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"context" "review_context" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_grammar_progress" (
	"user_id" uuid NOT NULL,
	"concept_id" integer NOT NULL,
	"status" "grammar_progress_status" NOT NULL,
	"studied_at" timestamp with time zone,
	CONSTRAINT "user_grammar_progress_user_id_concept_id_pk" PRIMARY KEY("user_id","concept_id")
);
--> statement-breakpoint
CREATE TABLE "user_reading_progress" (
	"user_id" uuid NOT NULL,
	"passage_id" integer NOT NULL,
	"times_read" integer DEFAULT 0 NOT NULL,
	"completed_at" timestamp with time zone,
	"last_read_at" timestamp with time zone,
	"tokens_looked_up" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "user_reading_progress_user_id_passage_id_pk" PRIMARY KEY("user_id","passage_id"),
	CONSTRAINT "user_reading_progress_counts_nonneg" CHECK ("user_reading_progress"."times_read" >= 0 and "user_reading_progress"."tokens_looked_up" >= 0)
);
--> statement-breakpoint
CREATE TABLE "user_word_progress" (
	"user_id" uuid NOT NULL,
	"lemma_id" integer NOT NULL,
	"correct_count" integer DEFAULT 0 NOT NULL,
	"incorrect_count" integer DEFAULT 0 NOT NULL,
	"difficulty" real,
	"stability" real,
	"interval_days" real,
	"next_review_at" timestamp with time zone,
	"last_reviewed_at" timestamp with time zone,
	"lookups_count" integer DEFAULT 0 NOT NULL,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_word_progress_user_id_lemma_id_pk" PRIMARY KEY("user_id","lemma_id"),
	CONSTRAINT "user_word_progress_counts_nonneg" CHECK ("user_word_progress"."correct_count" >= 0 and "user_word_progress"."incorrect_count" >= 0 and "user_word_progress"."lookups_count" >= 0),
	CONSTRAINT "user_word_progress_interval_nonneg" CHECK ("user_word_progress"."interval_days" is null or "user_word_progress"."interval_days" >= 0)
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"experience_level" "experience_level",
	"daily_minutes" smallint,
	"onboarded_at" timestamp with time zone,
	"disclosure_level" "disclosure_level" DEFAULT 'beginner' NOT NULL,
	CONSTRAINT "users_daily_minutes_range" CHECK ("users"."daily_minutes" is null or "users"."daily_minutes" between 1 and 240)
);
--> statement-breakpoint
CREATE TABLE "lemmas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lemmas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lemma" text NOT NULL,
	"gloss" text,
	"extended_gloss" text,
	"part_of_speech" "part_of_speech",
	"nt_frequency" integer DEFAULT 0 NOT NULL,
	"gloss_source_id" integer,
	CONSTRAINT "lemmas_lemma_unique" UNIQUE("lemma"),
	CONSTRAINT "lemmas_nt_frequency_nonneg" CHECK ("lemmas"."nt_frequency" >= 0),
	CONSTRAINT "lemmas_gloss_has_source" CHECK ("lemmas"."gloss" is null or "lemmas"."gloss_source_id" is not null)
);
--> statement-breakpoint
CREATE TABLE "morphology" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "morphology_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pos_code" text NOT NULL,
	"parse_code" text NOT NULL,
	"part_of_speech" "part_of_speech" NOT NULL,
	"person" "person",
	"tense" "tense",
	"voice" "voice",
	"mood" "mood",
	"case" "grammatical_case",
	"number" "grammatical_number",
	"gender" "gender",
	"degree" "degree",
	CONSTRAINT "morphology_pos_parse_unique" UNIQUE("pos_code","parse_code"),
	CONSTRAINT "morphology_pos_code_len" CHECK (char_length("morphology"."pos_code") = 2),
	CONSTRAINT "morphology_parse_code_len" CHECK (char_length("morphology"."parse_code") = 8)
);
--> statement-breakpoint
CREATE TABLE "data_sources" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "data_sources_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" text NOT NULL,
	"name" text NOT NULL,
	"version" text,
	"licence" text NOT NULL,
	"attribution" text NOT NULL,
	"url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "data_sources_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "books" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "books_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"abbrev" text NOT NULL,
	"canonical_order" integer NOT NULL,
	"testament" "testament" NOT NULL,
	CONSTRAINT "books_abbrev_unique" UNIQUE("abbrev"),
	CONSTRAINT "books_testament_order_unique" UNIQUE("testament","canonical_order"),
	CONSTRAINT "books_canonical_order_positive" CHECK ("books"."canonical_order" > 0)
);
--> statement-breakpoint
CREATE TABLE "chapters" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chapters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"book_id" integer NOT NULL,
	"number" integer NOT NULL,
	CONSTRAINT "chapters_book_number_unique" UNIQUE("book_id","number"),
	CONSTRAINT "chapters_number_positive" CHECK ("chapters"."number" > 0)
);
--> statement-breakpoint
CREATE TABLE "tokens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"verse_id" integer NOT NULL,
	"position" integer NOT NULL,
	"surface" text NOT NULL,
	"word" text NOT NULL,
	"normalized" text NOT NULL,
	"lemma_id" integer NOT NULL,
	"morphology_id" integer NOT NULL,
	"source_id" integer NOT NULL,
	CONSTRAINT "tokens_verse_position_unique" UNIQUE("verse_id","position"),
	CONSTRAINT "tokens_position_positive" CHECK ("tokens"."position" > 0)
);
--> statement-breakpoint
CREATE TABLE "verses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "verses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"chapter_id" integer NOT NULL,
	"number" integer NOT NULL,
	"ref" text NOT NULL,
	"ordinal" integer NOT NULL,
	CONSTRAINT "verses_ref_unique" UNIQUE("ref"),
	CONSTRAINT "verses_ordinal_unique" UNIQUE("ordinal"),
	CONSTRAINT "verses_chapter_number_unique" UNIQUE("chapter_id","number"),
	CONSTRAINT "verses_number_positive" CHECK ("verses"."number" > 0)
);
--> statement-breakpoint
ALTER TABLE "grammar_concept_examples" ADD CONSTRAINT "grammar_concept_examples_concept_id_grammar_concepts_id_fk" FOREIGN KEY ("concept_id") REFERENCES "public"."grammar_concepts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grammar_concept_examples" ADD CONSTRAINT "grammar_concept_examples_token_id_tokens_id_fk" FOREIGN KEY ("token_id") REFERENCES "public"."tokens"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grammar_concept_rules" ADD CONSTRAINT "grammar_concept_rules_concept_id_grammar_concepts_id_fk" FOREIGN KEY ("concept_id") REFERENCES "public"."grammar_concepts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lesson_items" ADD CONSTRAINT "lesson_items_lesson_id_lessons_id_fk" FOREIGN KEY ("lesson_id") REFERENCES "public"."lessons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lesson_items" ADD CONSTRAINT "lesson_items_lemma_id_lemmas_id_fk" FOREIGN KEY ("lemma_id") REFERENCES "public"."lemmas"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lesson_items" ADD CONSTRAINT "lesson_items_concept_id_grammar_concepts_id_fk" FOREIGN KEY ("concept_id") REFERENCES "public"."grammar_concepts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lesson_items" ADD CONSTRAINT "lesson_items_passage_id_passages_id_fk" FOREIGN KEY ("passage_id") REFERENCES "public"."passages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lessons" ADD CONSTRAINT "lessons_passage_id_passages_id_fk" FOREIGN KEY ("passage_id") REFERENCES "public"."passages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "passage_required_concepts" ADD CONSTRAINT "passage_required_concepts_passage_id_passages_id_fk" FOREIGN KEY ("passage_id") REFERENCES "public"."passages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "passage_required_concepts" ADD CONSTRAINT "passage_required_concepts_concept_id_grammar_concepts_id_fk" FOREIGN KEY ("concept_id") REFERENCES "public"."grammar_concepts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "passages" ADD CONSTRAINT "passages_start_verse_id_verses_id_fk" FOREIGN KEY ("start_verse_id") REFERENCES "public"."verses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "passages" ADD CONSTRAINT "passages_end_verse_id_verses_id_fk" FOREIGN KEY ("end_verse_id") REFERENCES "public"."verses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_events" ADD CONSTRAINT "review_events_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_events" ADD CONSTRAINT "review_events_lemma_id_lemmas_id_fk" FOREIGN KEY ("lemma_id") REFERENCES "public"."lemmas"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_grammar_progress" ADD CONSTRAINT "user_grammar_progress_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_grammar_progress" ADD CONSTRAINT "user_grammar_progress_concept_id_grammar_concepts_id_fk" FOREIGN KEY ("concept_id") REFERENCES "public"."grammar_concepts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_reading_progress" ADD CONSTRAINT "user_reading_progress_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_reading_progress" ADD CONSTRAINT "user_reading_progress_passage_id_passages_id_fk" FOREIGN KEY ("passage_id") REFERENCES "public"."passages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_word_progress" ADD CONSTRAINT "user_word_progress_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_word_progress" ADD CONSTRAINT "user_word_progress_lemma_id_lemmas_id_fk" FOREIGN KEY ("lemma_id") REFERENCES "public"."lemmas"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lemmas" ADD CONSTRAINT "lemmas_gloss_source_id_data_sources_id_fk" FOREIGN KEY ("gloss_source_id") REFERENCES "public"."data_sources"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chapters" ADD CONSTRAINT "chapters_book_id_books_id_fk" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tokens" ADD CONSTRAINT "tokens_verse_id_verses_id_fk" FOREIGN KEY ("verse_id") REFERENCES "public"."verses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tokens" ADD CONSTRAINT "tokens_lemma_id_lemmas_id_fk" FOREIGN KEY ("lemma_id") REFERENCES "public"."lemmas"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tokens" ADD CONSTRAINT "tokens_morphology_id_morphology_id_fk" FOREIGN KEY ("morphology_id") REFERENCES "public"."morphology"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tokens" ADD CONSTRAINT "tokens_source_id_data_sources_id_fk" FOREIGN KEY ("source_id") REFERENCES "public"."data_sources"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "verses" ADD CONSTRAINT "verses_chapter_id_chapters_id_fk" FOREIGN KEY ("chapter_id") REFERENCES "public"."chapters"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "review_events_user_reviewed_idx" ON "review_events" USING btree ("user_id","reviewed_at");--> statement-breakpoint
CREATE INDEX "user_word_progress_due_idx" ON "user_word_progress" USING btree ("user_id","next_review_at");--> statement-breakpoint
CREATE INDEX "lemmas_nt_frequency_idx" ON "lemmas" USING btree ("nt_frequency" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "tokens_lemma_idx" ON "tokens" USING btree ("lemma_id");--> statement-breakpoint
CREATE INDEX "tokens_morphology_idx" ON "tokens" USING btree ("morphology_id");