CREATE TABLE "reading_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reading_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"passage_id" integer NOT NULL,
	"completed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"tokens_read" integer NOT NULL,
	CONSTRAINT "reading_events_tokens_nonneg" CHECK ("reading_events"."tokens_read" >= 0)
);
--> statement-breakpoint
ALTER TABLE "reading_events" ADD CONSTRAINT "reading_events_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reading_events" ADD CONSTRAINT "reading_events_passage_id_passages_id_fk" FOREIGN KEY ("passage_id") REFERENCES "public"."passages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "reading_events_user_completed_idx" ON "reading_events" USING btree ("user_id","completed_at");