/**
 * Hand-written glosses (source "curated") for every word in the curated passages, so the
 * words a learner actually meets read naturally. Dodson's entries stay as the extended gloss
 * (DECISIONS 031).
 *
 * House style:
 * - verbs as "to …", nouns without an English article;
 * - the sense the passages use comes first;
 * - British spelling;
 * - short enough for an answer button (30 characters or fewer).
 * A test checks the style and that every lemma in a curated passage has one.
 */
export const curatedGlosses: Record<string, string> = {
  // Article, pronouns and particles
  ὁ: "the",
  αὐτός: "he, she, it; self, same",
  σύ: "you",
  ἐγώ: "I, me; we, us",
  κἀγώ: "and I, I also",
  ἑαυτοῦ: "himself, ourselves, oneself",
  ἐμαυτοῦ: "myself",
  ἀλλήλων: "one another",
  ὅς: "who, which, that",
  ὅστις: "who, whoever",
  ὅσος: "as many as, as much as",
  οὗτος: "this, this one",
  ἐκεῖνος: "that, that one",
  τοιοῦτος: "such, of this kind",
  τις: "someone, anyone, a certain",
  ἄν: "-ever (whoever, whatever)",
  ἴδε: "look! see!",
  ἀμήν: "truly, amen",

  // Conjunctions
  καί: "and, also, even",
  δέ: "but, and",
  ὅτι: "that, because",
  γάρ: "for, because",
  ἵνα: "so that, in order that",
  ἀλλά: "but, rather",
  ὡς: "as, like; when",
  εἰ: "if",
  ἐάν: "if, whenever",
  κἄν: "and if, even if",
  καθώς: "just as",
  οὐδέ: "and not, nor, not even",
  ὅτε: "when",
  ὥστε: "so that, therefore",
  ὅπου: "where",

  // Prepositions
  ἐν: "in, on, among; by",
  εἰς: "into, to, for",
  ἐκ: "out of, from",
  ἐπί: "on, upon, over, at",
  πρός: "to, toward, with",
  διά: "through; because of",
  ἀπό: "from, away from",
  μετά: "with; after",
  περί: "about, concerning; around",
  ὑπό: "by; under",
  παρά: "from; beside, with",
  ὑπέρ: "for, on behalf of; above",
  ἔμπροσθεν: "before, in front of",
  χωρίς: "without, apart from",
  ὀπίσω: "after, behind",
  ἀντί: "in place of, instead of",

  // Adverbs
  οὐ: "not, no",
  μή: "not, don't",
  "οὕτω(ς)": "so, thus, in this way",
  νῦν: "now",
  πάλιν: "again",
  πῶς: "how?",
  ἔτι: "still, yet",
  ἤδη: "already, now",
  οὐκέτι: "no longer",
  ποῦ: "where?",
  ἐπαύριον: "the next day",

  // Nouns
  θεός: "God, a god",
  λόγος: "word, message",
  ἀρχή: "beginning; ruler",
  Ἰησοῦς: "Jesus",
  κύριος: "Lord, master, sir",
  ἄνθρωπος: "person, human, man",
  Χριστός: "Christ, Messiah",
  πατήρ: "father",
  ἡμέρα: "day",
  πνεῦμα: "spirit, Spirit; breath",
  υἱός: "son",
  οὐρανός: "heaven, sky",
  μαθητής: "disciple, learner",
  πίστις: "faith, trust",
  ὄνομα: "name",
  ἀνήρ: "man, husband",
  νόμος: "law",
  κόσμος: "world",
  χείρ: "hand",
  ἁμαρτία: "sin",
  δόξα: "glory, honour",
  βασιλεία: "kingdom, reign",
  καρδία: "heart",
  χάρις: "grace, favour",
  σάρξ: "flesh",
  φωνή: "voice, sound",
  ζωή: "life",
  Ἰωάννης: "John",
  αἰών: "age, eternity",
  ἀγάπη: "love",
  ἀλήθεια: "truth",
  ὥρα: "hour, time",
  ψυχή: "life, soul, self",
  ἐξουσία: "authority, right, power",
  ὁδός: "way, road",
  ὀφθαλμός: "eye",
  τέκνον: "child",
  αἷμα: "blood",
  τόπος: "place",
  οἰκία: "house, household",
  θάλασσα: "sea, lake",
  καιρός: "time, season",
  Μωϋσῆς: "Moses",
  ὕδωρ: "water",
  εὐαγγέλιον: "good news, gospel",
  φῶς: "light",
  σάββατον: "Sabbath; week",
  Ἰσραήλ: "Israel",
  δαιμόνιον: "demon",
  γραμματεύς: "scribe, teacher of the law",
  θέλημα: "will, desire",
  ὄρος: "mountain, hill",
  Γαλιλαία: "Galilee",
  συναγωγή: "synagogue, assembly",
  ἀνάστασις: "resurrection",
  πρόβατον: "sheep",
  μαρτυρία: "testimony, witness",
  διδαχή: "teaching",
  ἀδικία: "wrongdoing, unrighteousness",
  σωτήρ: "saviour",
  κοινωνία: "fellowship, sharing",
  ποιμήν: "shepherd",
  πλήρωμα: "fullness",
  σκοτία: "darkness",
  Καφαρναούμ: "Capernaum",
  Ἰορδάνης: "Jordan (river)",
  Θωμᾶς: "Thomas",
  περιστερά: "dove",
  ψεύστης: "liar",
  τεκνίον: "little child",
  παράκλητος: "advocate, helper",
  Ναζαρέτ: "Nazareth",
  ἀμνός: "lamb",
  μονή: "room, dwelling place",
  ἱλασμός: "atoning sacrifice",
  προσκυνητής: "worshipper",

  // Adjectives and numerals
  πᾶς: "all, every, whole",
  εἷς: "one",
  δύο: "two",
  δώδεκα: "twelve",
  πολύς: "much, many",
  μέγας: "great, large",
  ἅγιος: "holy",
  οὐδείς: "no one, nothing",
  πρῶτος: "first",
  ἴδιος: "one's own",
  μόνος: "only, alone",
  ὅλος: "whole, all",
  καλός: "good, beautiful",
  δίκαιος: "righteous, just",
  ἐμός: "my, mine",
  ἡμέτερος: "our",
  αἰώνιος: "eternal",
  πιστός: "faithful, trustworthy",
  ἀγαπητός: "beloved, dear",
  εὐθύς: "immediately; straight",
  μικρός: "small, little",
  ἀληθινός: "true, real",
  ἐκλεκτός: "chosen",
  πλήρης: "full",
  μονογενής: "only, one and only",
  ὀρφανός: "orphaned; orphan",

  // Verbs
  εἰμί: "to be, exist",
  λέγω: "to say, speak, tell",
  ἔχω: "to have, hold",
  γίνομαι: "to become, happen, be",
  ἔρχομαι: "to come, go",
  ποιέω: "to do, make",
  ὁράω: "to see, perceive",
  ἀκούω: "to hear, listen",
  δίδωμι: "to give",
  λαλέω: "to speak, talk",
  οἶδα: "to know",
  λαμβάνω: "to take, receive",
  πιστεύω: "to believe, trust",
  ἀποκρίνομαι: "to answer, reply",
  γινώσκω: "to know, come to know",
  δύναμαι: "to be able, can",
  θέλω: "to want, wish",
  γράφω: "to write",
  δέω: "to be necessary, must; bind",
  ἵστημι: "to stand; to set",
  πορεύομαι: "to go, travel",
  ἀγαπάω: "to love",
  ἀφίημι: "to forgive, leave, let go",
  ζάω: "to live",
  βλέπω: "to see, look at",
  ἀποστέλλω: "to send (out)",
  βάλλω: "to throw, put",
  παραδίδωμι: "to hand over, betray",
  μένω: "to remain, stay, abide",
  ζητέω: "to seek, look for",
  ἀπέρχομαι: "to go away, leave",
  κρίνω: "to judge",
  ἀποθνῄσκω: "to die",
  σῴζω: "to save, heal",
  αἴρω: "to lift, take away",
  τίθημι: "to put, place, lay down",
  γεννάω: "to beget; (passive) be born",
  διδάσκω: "to teach",
  περιπατέω: "to walk, live",
  ἀπόλλυμι: "to destroy, lose; perish",
  ἀκολουθέω: "to follow",
  πληρόω: "to fill, fulfil",
  προσεύχομαι: "to pray",
  ἀναβαίνω: "to go up, come up",
  ἐκβάλλω: "to throw out, drive out",
  καταβαίνω: "to come down, go down",
  πέμπω: "to send",
  ὑπάγω: "to go away, depart",
  βαπτίζω: "to baptise, immerse",
  μαρτυρέω: "to testify, bear witness",
  αἰτέω: "to ask (for)",
  κηρύσσω: "to proclaim, preach",
  προσκυνέω: "to worship",
  θεωρέω: "to see, watch",
  κράζω: "to cry out, shout",
  παραλαμβάνω: "to receive, take along",
  φανερόω: "to reveal, make known",
  ἀπαγγέλλω: "to announce, report",
  ἁμαρτάνω: "to sin",
  ἐγγίζω: "to come near, approach",
  ἑτοιμάζω: "to prepare",
  πλανάω: "to deceive, lead astray",
  μετανοέω: "to repent, change one's mind",
  καθαρίζω: "to cleanse, make clean",
  φαίνω: "to shine; appear",
  προσκαλέομαι: "to call to oneself, summon",
  ὁμολογέω: "to confess, acknowledge",
  θεάομαι: "to see, behold",
  εὐδοκέω: "to be pleased, delight",
  διακρίνω: "to doubt; discern",
  εἰσπορεύομαι: "to go in, enter",
  ταράσσω: "to trouble, stir up",
  ἁρπάζω: "to snatch, seize",
  καταλαμβάνω: "to overcome, grasp",
  ἐκπλήσσομαι: "to be amazed",
  σχίζω: "to tear, split",
  φωτίζω: "to give light to",
  ἐμβλέπω: "to look at, gaze at",
  σκηνόω: "to dwell, pitch one's tent",
  ψηλαφάω: "to touch, handle",
};
